//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::session::Entity as Session;
pub use super::user::Entity as User;
